[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpeg" # gif files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.svg" # gif files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"